### ISSUE TITLE
Multiple Implementations of Method

### ISSUE THREAD

**Issue by jvbsl** [Firwood-Software/AdvanceDLSupport#59]
**Describe the bug**
I don't actually know if it is a problem with AdvanceDLSupport or the current code in OpenTK.
But I tried https://github.com/Nihlus/opentk/tree/al-adl with a really simple OpenAL test project which just tries to create ALContext at runtime.

Problem is that 
https://github.com/Firwood-Software/AdvanceDLSupport/blob/1167a435759046c325d5e5f49923aff80433c367/AdvancedDLSupport/NativeLibraryBuilder.cs#L226
`classType.GetInterfaces()`
returns 7 Interfaces for me:
[0] = {RuntimeType} "System.IDisposable"
[1] = {RuntimeType} "OpenTK.OpenAL.Interfaces.IALC"
[2] = {RuntimeType} "OpenTK.OpenAL.Interfaces.IContext"
[3] = {RuntimeType} "OpenTK.OpenAL.Interfaces.IContextDevices"
[4] = {RuntimeType} "OpenTK.OpenAL.Interfaces.IContextErrors"
[5] = {RuntimeType} "OpenTK.OpenAL.Interfaces.IContextExtensions"
[6] = {RuntimeType} "OpenTK.OpenAL.Interfaces.IContextState"

which kinda does make sense, with following class structure:
`public abstract class ALContext : NativeLibraryBase, IALC`
where
`internal interface IALC : IContext, IContextDevices, IContextErrors, IContextExtensions, IContextState`

so we get a flat structure of all the interfaces. But after that we will read all methods per interface in a flat structure as well, meaning IALC will yield all methods, contained in implemented interfaces like IContext.
https://github.com/Firwood-Software/AdvanceDLSupport/blob/1167a435759046c325d5e5f49923aff80433c367/AdvancedDLSupport/NativeLibraryBuilder.cs#L578
e.g. CreateContext method will be created. Later on after that the IContext interface is searched and we'll find the CreateContext method again and will create it again as well with completly the same signature. Which obviously is not allowed in IL and throws an Exception:

`System.TypeLoadException: Method 'CreateContext' on type 'Generated_ALContext_ada0976a_f17a_4000_b25f_76adbcb712db' from assembly 'DLSupportDynamicAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is overriding a method that has been overridden.`

Edit: Actually I found out that the problem was introduced with following commit:
https://github.com/Firwood-Software/AdvanceDLSupport/commit/14af9f8f839a1689dbfda2e915d080cdc2a998f6#diff-985c2f29072740d4022c57beb36d066dR574

I think the solution should be either to either not flattenHierarchy in GetIntrospectiveMethods call by passing false. Or not iterating over the given interfaces but using classType.GetIntrospectiveMethods(true) instead.
While I think the fist solution should be the better one.
https://github.com/Firwood-Software/AdvanceDLSupport/blob/1167a435759046c325d5e5f49923aff80433c367/AdvancedDLSupport/NativeLibraryBuilder.cs#L578

**To Reproduce**
1. Clone https://github.com/Nihlus/opentk/
2. and switch to al-adl branch
3. Simple test project with following code in main:
`ALContext context = ALContext.GetAPI();`

@Nihlus I'm cheeky enough to not post a minimal example, because I guess you are working on OpenTK as well and it should be much easier to debug it directly inside OpenTK... 

**Expected behavior**
Creating the class successfully at runtime.

**Desktop:**
 - OS: Linux 64 Bit
 - Runtime NET Core
 - Version 2.1.403

**Comment by morguldir** [comment]
Already fixed by #54

**Comment by Nihlus** [comment]
Thank you for the extremely detailed bug report! I wish more people took the time to make as good reports as this :D

As @morguldir stated, this bug should already be fixed. It might be that I haven't updated the al-adl branch to the latest release yet - could you try updating it via nuget, and testing again?

**Comment by jvbsl** [comment]
God damnit you are right. All this searching just because I was too stupid too update the nuget package -.-
Well apart from that it still does not work, but that should be a problem on OpenTK side. I'm gonna post it there.
Thanks
